# fly.toml app configuration file generated for zhongli on 2023-08-11T22:14:23+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "zhongli"
primary_region = "lhr"

[build]

[[services]]
  protocol = "tcp"
  internal_port = 8080
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
